apiVersion: batch/v1
kind: Job
metadata:
  name: NAME
spec:
  ttlSecondsAfterFinished: 90
  template:
    spec:
      containers:
      - name: NAME
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 4Gi
        image: turbobkupchild:0.1
        imagePullPolicy: Never
        command: [COMMAND]
        volumeMounts:
        - mountPath: /turbo-backup
          name: turbo-backup
      restartPolicy: OnFailure
      activeDeadlineSeconds: 7200
      volumes:
      - name: turbo-backup
        persistentVolumeClaim:
          claimName: turbo-bkup
      imagePullSecrets:
      - name: tivolinick-pull-secret
      restartPolicy: Never
  backoffLimit: 4



