apiVersion: v1
kind: PersistentVolume
metadata:
  name: turbo-backup-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[datastore-wdc06-vm01] ndf-turbo3_1/ndf-turbo3_1.vmdk"
    fsType: ext4
