apiVersion: batch/v1
kind: Job
metadata:
  name: turborestore-parent
  namespace: turbobkup
spec:
  ttlSecondsAfterFinished: 90
  template:
    spec:
      imagePullSecrets:
      - name: tivolinick-pull-secret
      containers:
      - name: turborestore-parent
        image: turbobkupparent:0.1
        imagePullPolicy: Never
        command:
        - /scripts/runrestore.sh
        volumeMounts:
        - mountPath: /kubeconfig
          name: kubeconfig
        - mountPath: /config/job
          name: job
        - mountPath: /config/archive
          name: archive
      volumes:
      - name: kubeconfig
        secret:
          secretName: kube-secret
      # - name: turbocreds
      #   secret:
      #     secretName: turbo-creds
      - name: job
        configMap:
          name: job-yaml
      - name: archive
        configMap:
          name: archive
      restartPolicy: Never
      activeDeadlineSeconds: 9000

